import { useState } from 'react'
import { ArrowUpRight, CheckCircle2, Send } from 'lucide-react'
import { portfolioApi } from '../services/api'
import SectionHeader from './SectionHeader'

const blank = { name: '', email: '', subject: '', message: '' }
export default function Contact() { const [form, setForm] = useState(blank); const [status, setStatus] = useState({ type: '', message: '' }); const [loading, setLoading] = useState(false)
  const submit = async (event) => { event.preventDefault(); setLoading(true); setStatus({ type: '', message: '' }); try { await portfolioApi.contact(form); setForm(blank); setStatus({ type: 'success', message: 'Thank you — your message has been sent.' }) } catch (error) { setStatus({ type: 'error', message: error.message }) } finally { setLoading(false) } }
  return <section id="contact" className="section shell contact-section"><SectionHeader number="07" eyebrow="Start a conversation" title={<>Have an idea? <em>Let’s build it.</em></>} text="Send a message and I’ll get back to you as soon as I can." /><div className="contact-grid reveal"><div className="contact-aside"><p>I’m interested in junior software, backend, full-stack, and practical AI application opportunities.</p><a href="mailto:sheikf002@gmail.com">sheikf002@gmail.com <ArrowUpRight size={17} /></a></div><form className="contact-form" onSubmit={submit}><label>Name<input required minLength="2" maxLength="100" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label><label>Email<input required type="email" maxLength="255" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Subject<input required minLength="3" maxLength="200" value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} placeholder="What can I help with?" /></label><label>Message<textarea required minLength="10" maxLength="3000" value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="Tell me a little about your project or opportunity…" rows="5" /></label>{status.message && <p className={`form-status ${status.type}`}>{status.type === 'success' && <CheckCircle2 size={17} />}{status.message}</p>}<button className="button primary submit" disabled={loading}>{loading ? 'Sending…' : <>Send message <Send size={16} /></>}</button></form></div></section> }
